# -*- coding: utf-8 -*-
"""Numpy Analyzer .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mLayD6_Nh08qibSAWJX9WpLCjrpWiLWA
"""

import numpy as np


class DataAnalytics:
   """Menu-driven NumPy analyzer using OOP concepts."""


    def __init__(self):
        self.__array = None

    @classmethod
    def create_analyzer(cls):
        return cls()


    def get_array(self):
        return self.__array

    def set_array(self, array):
        self.__array = array

    def __check_array(self):
        if self.__array is None:
            print("Create an array first!")
            return False
        return True

    def __get_elements(self, count):
        while True:
            try:
                elements = list(map(int,input(f"Enter {count} elements for the array separated by space: " ).split(), ) )
                if len(elements) != count:
                    print(f"Please enter exactly {count} elements.")
                    continue
                return elements
            except ValueError:
                print("Please enter only integer values.")

    def create_array(self):
        print("\nSelect the type of array to create:")
        print("1. 1D Array")
        print("2. 2D Array")
        print("3. 3D Array")

        try:
            choice = int(input("Enter your choice: "))
        except ValueError:
            print("Please enter a valid choice.")
            return

        try:
            if choice == 1:
                size = int(input("Enter the number of elements: "))
                if size <= 0:
                    print("Size must be greater than 0.")
                    return
                elements = self.__get_elements(size)
                self.__array = np.array(elements)

            elif choice == 2:
                rows = int(input("Enter the number of rows: "))
                cols = int(input("Enter the number of columns: "))
                if rows <= 0 or cols <= 0:
                    print("Rows and columns must be greater than 0.")
                    return
                elements = self.__get_elements(rows * cols)
                self.__array = np.array(elements).reshape(rows, cols)

            elif choice == 3:
                depth = int(input("Enter the number of depth: "))
                rows = int(input("Enter the number of rows: "))
                cols = int(input("Enter the number of columns: "))
                if depth <= 0 or rows <= 0 or cols <= 0:
                    print("Dimensions must be greater than 0.")
                    return
                elements = self.__get_elements(depth * rows * cols)
                self.__array = np.array(elements).reshape(depth, rows, cols)

            else:
                print("Invalid choice!")
                return

            print("\nArray created successfully:")
            print(self.__array)
            self.__indexing_slicing()

        except ValueError:
            print("Please enter valid numeric values.")


    def __indexing_slicing(self):
        print("\nChoose an operation:")
        print("1. Indexing")
        print("2. Slicing")
        print("3. Go Back")

        try:
            choice = int(input("Enter your choice: "))
        except ValueError:
            print("Please enter a valid choice.")
            return

        try:
            if choice == 1:
                if self.__array.ndim == 1:
                    index = int(input("Enter the index: "))
                    print("\nElement at index", index, ":")
                    print(self.__array[index])

                elif self.__array.ndim == 2:
                    row = int(input("Enter the row index: "))
                    col = int(input("Enter the column index: "))
                    print(f"\nElement at [{row}, {col}]:")
                    print(self.__array[row, col])

                else:
                    depth = int(input("Enter the depth index: "))
                    row = int(input("Enter the row index: "))
                    col = int(input("Enter the column index: "))
                    print(f"\nElement at [{depth}, {row}, {col}]:")
                    print(self.__array[depth, row, col])

            elif choice == 2:
                if self.__array.ndim == 1:
                    value = input("Enter the range (start:end): ")
                    start, end = map(int, value.split(":"))
                    sliced_array = self.__array[start:end]

                elif self.__array.ndim == 2:
                    row_range = input("Enter the row range (start:end): ")
                    col_range = input("Enter the column range (start:end): ")
                    row_start, row_end = map(int, row_range.split(":"))
                    col_start, col_end = map(int, col_range.split(":"))
                    sliced_array = self.__array[row_start:row_end, col_start:col_end]

                else:
                    depth_range = input("Enter the depth range (start:end): ")
                    row_range = input("Enter the row range (start:end): ")
                    col_range = input("Enter the column range (start:end): ")
                    depth_start, depth_end = map(int, depth_range.split(":"))
                    row_start, row_end = map(int, row_range.split(":"))
                    col_start, col_end = map(int, col_range.split(":"))
                    sliced_array = self.__array[
                        depth_start:depth_end,
                        row_start:row_end,
                        col_start:col_end,
                    ]

                print("\nSliced Array:")
                print(sliced_array)

            elif choice == 3:
                return

            else:
                print("Invalid choice!")

        except (ValueError, IndexError):
            print("Please enter valid indexing/slicing values.")

    def mathematical_operations(self):
        if not self.__check_array():
            return

        print("\nChoose a mathematical operation:")
        print("1. Addition")
        print("2. Subtraction")
        print("3. Multiplication")
        print("4. Division")

        try:
            choice = int(input("Enter your choice: "))
        except ValueError:
            print("Please enter a valid choice.")
            return

        if choice not in (1, 2, 3, 4):
            print("Invalid choice!")
            return

        elements = self.__get_elements(self.__array.size)
        second_array = np.array(elements).reshape(self.__array.shape)

        print("\nOriginal Array:")
        print(self.__array)
        print("\nSecond Array:")
        print(second_array)

        if choice == 1:
            print("\nResult of Addition:")
            print(self.__array + second_array)
        elif choice == 2:
            print("\nResult of Subtraction:")
            print(self.__array - second_array)
        elif choice == 3:
            print("\nResult of Multiplication:")
            print(self.__array * second_array)
        else:
            if np.any(second_array == 0):
                print("\nDivision by zero is not allowed!")
            else:
                print("\nResult of Division:")
                print(self.__array / second_array)


    def combine_or_split_arrays(self):
        if not self.__check_array():
            return

        print("\nChoose an option:")
        print("1. Combine Arrays")
        print("2. Split Array")

        try:
            choice = int(input("Enter your choice: "))
        except ValueError:
            print("Please enter a valid choice.")
            return

        if choice == 1:
            elements = self.__get_elements(self.__array.size)
            second_array = np.array(elements).reshape(self.__array.shape)

            print("\nOriginal Array:")
            print(self.__array)
            print("\nSecond Array:")
            print(second_array)

            if self.__array.ndim == 1:
                combined = np.concatenate((self.__array, second_array))
            else:
                combined = np.vstack((self.__array, second_array))

            print("\nCombined Array (Vertical Stack):")
            print(combined)

        elif choice == 2:
            split_arrays = np.array_split(self.__array, 2, axis=0)
            print("\nOriginal Array:")
            print(self.__array)
            print("\nSplit Array 1:")
            print(split_arrays[0])
            print("\nSplit Array 2:")
            print(split_arrays[1])

        else:
            print("Invalid choice!")

    def search_sort_filter(self):
        if not self.__check_array():
            return

        print("\nChoose an option:")
        print("1. Search a value")
        print("2. Sort the array")
        print("3. Filter values")

        try:
            choice = int(input("Enter your choice: "))
        except ValueError:
            print("Please enter a valid choice.")
            return

        if choice == 1:
            try:
                value = int(input("Enter value to search: "))
                if np.any(self.__array == value):
                    print("Value Found")
                else:
                    print("Value Not Found")
            except ValueError:
                print("Please enter a valid number.")

        elif choice == 2:
            print("\nOriginal Array:")
            print(self.__array)

            sorted_array = np.sort(self.__array, axis=-1)
            print("\nSorted Array:")
            print(sorted_array)
            print("(Sorting applied row-wise.)")

        elif choice == 3:
            try:
                value = int(input("Show values greater than: "))
                print("\nFiltered Values:")
                print(self.__array[self.__array > value])
            except ValueError:
                print("Please enter a valid number.")

        else:
            print("Invalid choice!")


    def aggregate_statistics(self):
        if not self.__check_array():
            return

        print("\nChoose an aggregate/statistical operation:")
        print("1. Sum")
        print("2. Mean")
        print("3. Median")
        print("4. Standard Deviation")
        print("5. Variance")

        try:
            choice = int(input("Enter your choice: "))
        except ValueError:
            print("Please enter a valid choice.")
            return

        print("\nOriginal Array:")
        print(self.__array)

        if choice == 1:
            print("\nSum of Array:", np.sum(self.__array))
        elif choice == 2:
            print("\nMean of Array:", np.mean(self.__array))
        elif choice == 3:
            print("\nMedian of Array:", np.median(self.__array))
        elif choice == 4:
            print("\nStandard Deviation of Array:", np.std(self.__array))
        elif choice == 5:
            print("\nVariance of Array:", np.var(self.__array))
        else:
            print("Invalid choice!")


    def run(self):
        print("\nWelcome to the NumPy Analyzer!")
        print("========================================")

        while True:
            print("Choose an option:")
            print("1. Create a Numpy Array")
            print("2. Perform Mathematical Operations")
            print("3. Combine or Split Arrays")
            print("4. Search, Sort, or Filter Arrays")
            print("5. Compute Aggregates and Statistics")
            print("6. Exit")

            try:
                choice = int(input("Enter your choice: "))
            except ValueError:
                print("Please enter a valid number.")
                continue

            if choice == 1:
                self.create_array()
            elif choice == 2:
                self.mathematical_operations()
            elif choice == 3:
                self.combine_or_split_arrays()
            elif choice == 4:
                self.search_sort_filter()
            elif choice == 5:
                self.aggregate_statistics()
            elif choice == 6:
                print("\nThank you for using the NumPy Analyzer! Goodbye!")
                break
            else:
                print("Invalid Choice!")



analyzer = DataAnalytics.create_analyzer()
analyzer.run()