# -*- coding: utf-8 -*-
"""Numpy Analyzer .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mLayD6_Nh08qibSAWJX9WpLCjrpWiLWA
"""

import numpy as np

arr = None

while True:
    print("\n========== NumPy Analyzer ==========")
    print("1. Create a NumPy Array")
    print("2. Perform Mathematical Operations")
    print("3. Combine or Split Arrays")
    print("4. Search, Sort, or Filter Arrays")
    print("5. Compute Aggregates and Statistics")
    print("6. Exit")

    choice = int(input("Enter your choice: "))

    if choice == 1:
        rows = int(input("Enter number of rows: "))
        cols = int(input("Enter number of columns: "))
        elements = list(map(int, input(f"Enter {rows*cols} elements separated by space: ").split()))
        arr = np.array(elements).reshape(rows, cols)
        print("\nArray created successfully:")
        print(arr)

    elif choice == 2:
        if arr is None:
            print("Create an array first!")
            continue

        print("\n1. Addition")
        print("2. Subtraction")
        print("3. Multiplication")
        print("4. Division")
        op = int(input("Enter your choice: "))

        elements = list(map(int, input(f"Enter {arr.size} elements separated by space: ").split()))
        arr2 = np.array(elements).reshape(arr.shape)

        print("\nOriginal Array:")
        print(arr)
        print("\nSecond Array:")
        print(arr2)

        if op == 1:
            print("\nResult:")
            print(arr + arr2)
        elif op == 2:
            print("\nResult:")
            print(arr - arr2)
        elif op == 3:
            print("\nResult:")
            print(arr * arr2)
        elif op == 4:
            print("\nResult:")
            print(arr / arr2)

    elif choice == 3:
        if arr is None:
            print("Create an array first!")
            continue

        print("\n1. Combine Arrays")
        ch = int(input("Enter your choice: "))

        if ch == 1:
            elements = list(map(int, input(f"Enter {arr.size} elements separated by space: ").split()))
            arr2 = np.array(elements).reshape(arr.shape)
            print("\nCombined Array:")
            print(np.vstack((arr, arr2)))

    elif choice == 4:
        if arr is None:
            print("Create an array first!")
            continue

        print("\n1. Search")
        print("2. Sort")
        print("3. Filter")
        ch = int(input("Enter your choice: "))

        if ch == 1:
            value = int(input("Enter value to search: "))
            if value in arr:
                print("Value Found")
            else:
                print("Value Not Found")

        elif ch == 2:
            print("\nSorted Array:")
            print(np.sort(arr))

        elif ch == 3:
            value = int(input("Show values greater than: "))
            print(arr[arr > value])

    elif choice == 5:
        if arr is None:
            print("Create an array first!")
            continue

        print("\n1. Sum")
        print("2. Mean")
        print("3. Median")
        print("4. Standard Deviation")
        print("5. Variance")

        ch = int(input("Enter your choice: "))

        if ch == 1:
            print("Sum =", np.sum(arr))
        elif ch == 2:
            print("Mean =", np.mean(arr))
        elif ch == 3:
            print("Median =", np.median(arr))
        elif ch == 4:
            print("Standard Deviation =", np.std(arr))
        elif ch == 5:
            print("Variance =", np.var(arr))

    elif choice == 6:
        print("Thank you for using the NumPy Analyzer! Goodbye!")
        break

    else:
        print("Invalid Choice!")